### ISSUE TITLE
Bug: "Submit" button in comment section abruptly drops below comment preview

### ISSUE THREAD

**Issue by waitgain** [TheRealGD/therealgd#102]
When leaving a comment, a preview is shown below the comment box. However, there's a slight delay between finishing my comment and the preview appearing, causing the submit button to abruptly "drop" below the preview. The submit button should remain static throughout the entire commenting process.

**Comment by TKsM151** [comment]
To solve for this I would have to move the button above the preview or just remove the preview all together from comments.

This is mainly a display for if you used the wiki syntax in your comment.

Let me know what you think would be the best solve

**Comment by waitgain** [comment]
See #issue-references (discord) screen cap - entitled "Github ticket #102"

**Comment by TKsM151** [comment]
Made it go back to the referrer isntead. It is good UX practice to drill back through bread crumbs
