### ISSUE TITLE
Feature: User inbox should retain comment replies after marked as "read". Also, Inbox icon should be shown at all times, not only when user has a notification

### ISSUE THREAD

**Issue by waitgain** [TheRealGD/therealgd#103]
I used another account to reply to a comment I made, and received the appropriate notification. However, once I marked it as read, the comment disappeared from existence.

I'd suggest being able to retain replies to user comments, albeit marked as "read" in the messages/envelope link under username.

**Comment by waitgain** [comment]
I also noticed that I must manually click "clear inbox" for the envelope notification to go away. It should automatically be marked as read when I click my envelope.

**Comment by waitgain** [comment]
I'd also suggest having the inbox/messages icon around at all times, and not only when a user has a notification.

**Comment by psineur** [comment]
@waitgain please open two separate issues for this and mention them here

**Comment by psineur** [comment]
Closed in https://github.com/TheRealGD/therealgd/pull/108

Opening 2 new suggested issues:
#120
#121
