### ISSUE TITLE
Add a couple of content pages for Privacy Policy, TOS, etc with links in the footer area

### ISSUE THREAD

**Issue by psineur** [TheRealGD/therealgd#11]
- [x] assign to UKyank
- [ ] prepare all legal materials in any format
- [x] modify templates/code with these materials

**Comment by psineur** [comment]
Moved from Task-Board for comments/discussion/assignment etc.

Originally created by @DEVxALMIGHTY assigned to DiscordUser: UKyank - please re-assign once we have the github name

**Comment by psineur** [comment]
huh, github doesn't allow me to assign this to @UKyank yet, maybe need to confirm email?

**Comment by psineur** [comment]
Touched in #22 and #23 - tracking...
I believe 3rd point in OP in this issue can be checked. 

@UKyank to update. 
BTW since were storing in wiki - we can save in this GitHub projects wiki the pages and close this issue. 

Then when we launch prod - we just re-create the pages.

**Comment by DEVxALMIGHTY** [comment]
@ukyank can you provide an update here ?
