### ISSUE TITLE
Bug: Clicking on deleted Post Links

### ISSUE THREAD

**Issue by Bartman383** [TheRealGD/therealgd#117]
![image](https://user-images.githubusercontent.com/37676219/38060187-4780c4fc-32af-11e8-8317-73191c7f15f5.png)

Clicking on a link to a deleted post returns

App\Entity\Submission object not found by the @Entity annotation. The expression "repository.findOneBy({forum: forum, id: submission_id})" returned null

**Comment by psineur** [comment]
need 404 instead

**Comment by TKsM151** [comment]
404s are the red pages by defauly in ENV=DEV, once switched to ENV=PROD the custom error page will display. See the custom error page here:

http://dodev.infringethis.com:8000/_error/404.twig

**Comment by TKsM151** [comment]
Moving to closed, should see comment above about PROD vs DEV environment display of 404s for Symfony
