### ISSUE TITLE
Bug(s): Issues when submitting a deal

### ISSUE THREAD

**Issue by waitgain** [TheRealGD/therealgd#118]
1. When I paste the URL (in this case for Palmetto State Armory), the title auto fills. I'd rather it be like reddit where it gives the option for "use suggested title" and not just auto fill.

2. If user accidentally submits without choosing a subforum, the correct subforum can no longer be chosen. The dropdown keeps saying "choose one"

Please see video "Ticket #118"

**Comment by psineur** [comment]
Moving 2) to separate issue that needs immediate attention

**Comment by psineur** [comment]
This issue still needs triaging for 1)

**Comment by psineur** [comment]
1) merge to #112 
2) is separate issue - #122 

Closed
