### ISSUE TITLE
Mobile options on comments not working 

### ISSUE THREAD

**Issue by Bartman383** [TheRealGD/therealgd#130]
@TKsM151 

Only "reply" works on mobile when responding to comments.  All the others return this

![](https://cdn.discordapp.com/attachments/428341913540755457/429044812277350410/Screenshot_20180329-172945.png)
#

**Comment by DEVxALMIGHTY** [comment]
Good catch. I see it in browser too.

![image](https://user-images.githubusercontent.com/37675911/38117192-4d9b8046-3379-11e8-85e6-b1abdbd279b2.png)
