### ISSUE TITLE
 Change Group modification submit button text to "Save Changes" from "Edit".

### ISSUE THREAD

**Issue by DEVxALMIGHTY** [TheRealGD/therealgd#139]
For the sake of clarity & consistency, change Group modification submit button text to "Save Changes" from "Edit".

# Change this
![image](https://user-images.githubusercontent.com/37675911/38147054-3fef90ca-3416-11e8-835f-453708f8e4af.png)

# To this
![image](https://user-images.githubusercontent.com/37675911/38147084-63bea73e-3416-11e8-8a5a-6043c397aaa0.png)

**Comment by danielgsims** [comment]
This was in the translations file, so it's updated for all buttons site-wide that used the phrase "Edit"

**Comment by danielgsims** [comment]
Sorry, I should have used the fixes reference, but this one was fixed by #147 147.
