### ISSUE TITLE
Navbar dropdown on hover instead of click

### ISSUE THREAD

**Issue by DEVxALMIGHTY** [TheRealGD/therealgd#141]
Have navbar's drop down menu show on hover rather than having to click.

![image](https://user-images.githubusercontent.com/37675911/38150960-f54c655a-3426-11e8-95e8-d99811b5a46b.png)

**Comment by danielgsims** [comment]
You probably want expand on hover in addition to click so that it works on touch devices or with keyboard usage. I'll take a peak at this.

**Comment by danielgsims** [comment]
For testing, this also effects the user drop down in the top right

**Comment by danielgsims** [comment]
Fixed by #146
