### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by psineur** [TheRealGD/therealgd#17]
We don't want to measure everything or dig deep into heatmaps, etc. 
But IMO we want the number of forum views / unique visitors/ DAU/MAU from Day One.

I think this could be pretty easily done with Google Analytics and TrackingID coming from Config/Env.

For actual implementation - we can just modify templates for posts and forums and provide forum name / submission url as a param to event / page-view.

GA Debug extension for chrome can be of great help. Should be moderately easy task for someone familiar with gtag.

**Comment by psineur** [comment]
This will be upforgrabs for at least few days - this task is great opportunity even for students / almost complete noobs to help.
Mention @psineur for codereview. 

If no one picks this up - I will take it after main devops/organization issues are worked on and pretty much almost before MVP release.

**Comment by psineur** [comment]
@TKsM151 started this in #24

We still need to needle-through the 'ga-1234-id' string from env->app->twig.

P.S. You can mention issues in commits with #24 as well - then they will appear in the log of the issue.
Something like


     git commit -m "Finish google analytics. Closes #17" 

will appear here and close the issue when merged.

**Comment by zoidbergjesus** [comment]
Happy to help out with this one. Analytics/Data Engineering in my wheelhouse

**Comment by psineur** [comment]
https://github.com/TheRealGD/therealgd/blob/0a68211fa877c1dc8ce6d1ef45845f68d66ca8f4/templates/_includes/site_tracking.html.twig#L8

this is not implemented yet fully - we need to pass tracking from config/env.

@zoidbergjesus you're on it.
Please accept org invite on https://github.com/orgs/TheRealGD and assign yourself to this issue.
Thank You!

**Comment by TKsM151** [comment]
also, PM me in discord some Gmail addresses to add to the analytics platform

**Comment by DEVxALMIGHTY** [comment]
I'm having a look around @ Google Analytics now - I'm blown away. Soo much valuable data here ... well, there will be once we actually get some real users.

**Comment by DEVxALMIGHTY** [comment]
Does this require any wiring on our end? Or does GA handle everything ?

**Comment by TKsM151** [comment]
Unaversal tags work as is with the basic tag.

There is more advanced shut we can do like gtm and custom events but that's future shut and would require some input from marketing types on where and how to target.

**Comment by TKsM151** [comment]
Sorry my spelling sucks

**Comment by TKsM151** [comment]
Also, server side stats you'd have to refer to one of the backend gus as to whats best, they can log and dump images to a page I think.

**Comment by psineur** [comment]
I think our current gtag is good enough for v1.

**Comment by psineur** [comment]
#165 for future non-MVP analytics
