### ISSUE TITLE
Load 5K posts to DB to observe DB & Postmill framework scaling

### ISSUE THREAD

**Issue by DEVxALMIGHTY** [TheRealGD/therealgd#28]
@nautbot Has latest 5K gundeals posts generated from @everlasted web scraper which pulled from the gundeals twitter bot.

This data (along with posts pulled using reddit bot "nautbot") needs to be put into database used by the Digital Ocean DEV server.

This will allow us to see how the Postmill framework will scale with a large number of posts using authentic data - "fail fast" & all that.

**Comment by TKsM151** [comment]
UPDATE: @everlasted is our savior on this one, he figured out a way to post them in, and wrote a quick script. we are just waiting on consolodated data for the complete set. Plan is to create a generic account and and post them all in from the generic account for the initial load.

**Comment by everlasted** [comment]
UPDATE: This has been completed, both on the DO box and on gundeals.io box. Total number of submitted posts ended up being closer to 3700 but they were eventually all loaded onto the site.

The gundeals.io box did not fetch thumbnails for each post, so the script may have to be re-run for that server.

**Comment by DEVxALMIGHTY** [comment]
@everlasted  Is this issue resolved? Did you forget to close ?

**Comment by NathanDeckinga** [comment]
If we decide to do this again, can you holler at me so I can check DB stuff while the load is happening?  I would like to watch it live if possible.

**Comment by psineur** [comment]
I've loaded 86K users with Fixtures from t2.2xlarge PHP to t2.micro RDS test db - db took it like a champ <25% CPU, with <70 simultaneous connections.
PHP was maxing out on CPU.

I think we can close this now - our performance bottleneck is PHP and ORM, not DB
