### ISSUE TITLE
Discuss how/where to store release artifacts.

### ISSUE THREAD

**Issue by DEVxALMIGHTY** [TheRealGD/therealgd#30]
How do we manage release artifacts ? Its critical to have a structured method for managing all versions of release artifacts.

I've used Artifactory in the past with Jenkins where some arbitrary content is published after build. Artifactory also has an extensive REST api in case we want to do things with the artifact after it is published such as deploy.

**Comment by psineur** [comment]
Export filesystem to zip? Or at least critical part of it with paths white/black-listing?

**Comment by DEVxALMIGHTY** [comment]
Sure that could work for our purposes.

I'll close this issue.
