### ISSUE TITLE
Allow submission of URLs with [, ], or | characters

### ISSUE THREAD

**Issue by everlasted** [TheRealGD/therealgd#37]
When submitting the old gundeals posts last night, I noticed there were a handful of links (maybe around 10 out of 3700?) that contained either `[`, `]`, or `|` characters, usually from longer URLs to like flyers or catalogs.

Postmill currently rejects these URLs as invalid and does not allow the user to submit them. While this is admittedly a rare case, it may be worthwhile to find where URL validity is checked and modify the conditions. Making those characters urlsafe (`%5B`, `%5D`, and `%7C` respectively) seems to work without issue.

**Comment by DEVxALMIGHTY** [comment]
Great catch & attention to detail here. Seems url-encoding the entire link is the way to go.
