### ISSUE TITLE
Document prod/dev/test non-local DB creation

### ISSUE THREAD

**Issue by psineur** [TheRealGD/therealgd#42]
Still holding more or less in memory how I setup RDS on Friday.
But here are some links I used just in case:

https://www.postgresql.org/docs/9.0/static/sql-alterdefaultprivileges.html
https://www.postgresql.org/docs/9.1/static/sql-alterdatabase.html
https://www.postgresql.org/docs/current/static/sql-grant.html#SQL-GRANT-DESCRIPTION-OBJECTS

https://dba.stackexchange.com/questions/117109/how-to-manage-default-privileges-for-users-on-a-database-vs-schema

TODO:
- [x] Make sure Aurora is overkill and report costs #34
- [x] Create new DB instances with minimal requirements gundeals
- [x] Document each step and commit to infra/db or docs/ - 
- [x] If docs/ are used - update index and distinguish local database
- [x] test / dev / prod
- [x] HOW TO CREATE dev_name DB for a single developer on shared cluster

**Comment by psineur** [comment]
On it

**Comment by psineur** [comment]
CREATE DATABASE therealgd_test;
CREATE ROLE gundealstest WITH LOGIN PASSWORD 'passfortestuser'
ALTER DATABASE therealgd_test OWNER TO gundealstest;

was enough to create test db and start playing with it

**Comment by DEVxALMIGHTY** [comment]
Task #29 is dependent on this. I'm waiting on db connection string.

**Comment by psineur** [comment]
Note: no need to redact this one - real usernames and passwords are removed

// Create Users
CREATE ROLE youwish_devuser WITH LOGIN PASSWORD 'oooh_heees_trying';
CREATE ROLE youwish_testuser WITH LOGIN PASSWORD 'oooh_heees_trying';
CREATE ROLE youwish_produser WITH LOGIN PASSWORD 'oooh_heees_trying';
CREATE ROLE youwish_prodadmin WITH LOGIN PASSWORD 'oooh_heees_trying';

// Give all other user's permissions to DB master/root user
GRANT youwish_devuser TO youwish_root;
GRANT youwish_testuser TO youwish_root;
GRANT youwish_produser TO youwish_root;
GRANT youwish_prodadmin TO youwish_root;

// Give admin prod role everything prod-readWrite has
GRANT youwish_produser TO youwish_prodadmin;

// Create Databases
CREATE DATABASE youwish_prod;
REVOKE ALL ON DATABASE youwish_prod FROM public;
CREATE DATABASE youwish_dev;
REVOKE ALL ON DATABASE youwish_dev FROM public;
CREATE DATABASE youwish_test;
REVOKE ALL ON DATABASE youwish_test FROM public;

// Prod and ProdAdmin can both connect to Prod, but Owner is ProdAdmin
ALTER DATABASE youwish_prod OWNER to youwish_prodadmin;
GRANT CONNECT ON DATABASE youwish_prod TO youwish_prodadmin;
GRANT CONNECT ON DATABASE youwish_prod TO youwish_produser;

// Dev and Test user===admin
ALTER DATABASE youwish_dev OWNER to youwish_devuser;
ALTER DATABASE youwish_test OWNER to youwish_testuser;
GRANT CONNECT ON DATABASE youwish_dev TO youwish_devuser;
GRANT CONNECT ON DATABASE youwish_test TO youwish_testuser;

// For each db - create schema and default priveleges 
\connect youwish_prod
CREATE SCHEMA schma AUTHORIZATION youwish_prodadmin;
SET search_path = schma;
ALTER ROLE youwish_prodadmin IN DATABASE youwish_prod SET search_path = schma;
ALTER ROLE youwish_produser IN DATABASE youwish_prod SET search_path = schma;
GRANT USAGE  ON SCHEMA schma TO youwish_produser;
GRANT CREATE ON SCHEMA schma TO youwish_prodadmin;
ALTER DEFAULT PRIVILEGES FOR ROLE youwish_prodadmin GRANT INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO youwish_prod;
ALTER DEFAULT PRIVILEGES FOR ROLE youwish_prodadmin GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO youwish_prod;
GRANT TEMP ON DATABASE youwish_prod TO youwish_produser;
// REPEAT STEPS ABOVE FOR test and dev, except combine roles since there is no admin/user distinction

@DEVxALMIGHTY sent you the url.

**Comment by psineur** [comment]
task is kill

**Comment by psineur** [comment]
see https://github.com/TheRealGD/therealgd/pull/54
