### ISSUE TITLE
Bug: Selecting 'GD theme' makes some text unreadable

### ISSUE THREAD

**Issue by DEVxALMIGHTY** [TheRealGD/therealgd#46]
When selecting "GD theme" in user settings when on night mode, some text disappears.
I'm guessing you need to change text color from black

![image](https://user-images.githubusercontent.com/37675911/37880797-69df4612-3053-11e8-8016-fa3e1c54d169.png)

**Comment by TKsM151** [comment]
Ah this is a crap testing artifact on my dev box, ill remove it

**Comment by DEVxALMIGHTY** [comment]
I've assigned it to @TKsM151 

You can close it when you're confident its fixed.

**Comment by TKsM151** [comment]
Removed custom theme from db
