### ISSUE TITLE
Attempting to view user comment history results in application 500 error: "undefined method"

### ISSUE THREAD

**Issue by 12462940548** [TheRealGD/therealgd#53]
When attempting to view a user's comment history, the application responds with a 500 error. This condition exists regardless of the user's authentication state. 

These are the errors received from the application when invoking that undefined method:
```
CRITICAL06:30:33 | php | Call to undefined method __TwigTemplate_74785b85f3d8d84a2d8dfa89c6b2a71aca788ec7a17101247f6e8c9cab0a07e7::macro_comment()

CRITICAL06:30:33 | request | Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "macro_comment" of class "__TwigTemplate_74785b85f3d8d84a2d8dfa89c6b2a71aca788ec7a17101247f6e8c9cab0a07e7"." at /home/postmill/therealgd/var/cache/dev/twig/84/8416cac490addbe8f2757ad9d08765c6501d4c6e0e511eb044ab6b6bab6113cb.php line 143
```

How to test:

1) browse to any existing user's comment page: http://dodev.infringethis.com:8000/user/Sam_Flynn/comments

2) experience 500 error
This method is currently broken externally from unauthenticated users as well as from authenticated users attempting to view their own comment history. 

Please note: this defect is not present on raddle.me and is a regression with our development environment or has been patched and not made it upstream.

**Comment by psineur** [comment]
Good issue for newcomer - comment that you're working on this and send a Pull Request

**Comment by 12462940548** [comment]
I don't know that I have the php experience to get this bug resolved in code, I am just logging it at this time so we can investigate further. It's possible it's environmental related, which I will try to discern.

**Comment by TKsM151** [comment]
strange but just had to rewrite how the twig macro was being included , unknown origin
