### ISSUE TITLE
Configure auto-deploy from Jenkins to DO box

### ISSUE THREAD

**Issue by DEVxALMIGHTY** [TheRealGD/therealgd#57]
I will configure Jenkins build to put required content on @TKsM151 DO box to result in successful code deployment. An automated deployment process allows developers to focus more on dev-related tasks (writing code, fixing bugs) and allows Jenkins to handle ops tasks (deployment). It also ensures the same process is followed for each release whereas doing it manually leaves room for process obfuscation.

## Standard release pipeline
1. Make final commit for upcoming release n.
2. Jenkins build for 'develop' automatically kicks off fetching required components, conducting unit tests & code quality scan. This build will **not** DEPLOY. Deployment option must manually be selected prior to manual triggering of the Jenkins build.
3. Upon successful completion of unit tests & scan verification, manually kick off 'develop' build. Select "DEPLOY" on this build. This will deploy to DEV server.
4. Verify functionality on DEV server.
5. Submit & fulfill PR: develop --> master.
6. Jenkins build for 'master' will automatically kick off due to SCM polling. It will **not** deploy to PROD server, only build the app. Deployment option must manually be selected prior to manual triggering of the Jenkins build.
7. Upon successful completion of unit tests & scan verification, manually kick off 'master' Release build. Select "DEPLOY" on this build. This will deploy to PROD server and generate a tag in the GitHub repo. A tag can be used as a "safe" point of reference in case we need to perform code revert.
8. You have now released & app is now live!

# Example - Deploy to DEV server from 'develop' Jenkins build
![image](https://user-images.githubusercontent.com/37675911/37912496-44da9364-30d8-11e8-8725-f751d95231c8.png)

# Example - Deploy to PROD server from 'master' Jenkins Release build
![image](https://user-images.githubusercontent.com/37675911/37922347-eb31a874-30f1-11e8-980d-159886c69e9b.png)

**Comment by DEVxALMIGHTY** [comment]
@kudakeru What do you think of the above release pipeline?

Room for improvement ?

**Comment by kudakeru** [comment]
I think once we establish the pipeline and prove it out, we could even eliminate the manual deployment piece, at least for pre-prod. We may still want to manually trigger production, at least for a while. As a high level view of the pipeline process, this looks good. I'd like to flesh out some of the specifics.

Do we have a written PR process? Something that defines how we want them to be structured and submitted in terms of rebasing/not rebasing, etc? For step 2, we can offset a growing storage problem by using something like the free version of Artifactory to store/cache all of the artifacts Jenkins has to retrieve for each build. That'll speed up builds, also. 

I typically think of a "dev" server as "whatever's most current in the develop branch", which could be in a number of states, but allows us to constantly iterate. That fits with just automatically deploying code as it gets pushed to that branch. That being said, it also makes it much messier to stage code before a production deployment. So we'll either want to more tightly control what gets pushed to dev, or have a staging environment. The former shortens the iteration loop during development, the latter adds cost.

**Comment by DEVxALMIGHTY** [comment]
Some thoughtful feedback here - thank you! I'll try to touch on each point you raised.

> I think once we establish the pipeline and prove it out, we could even eliminate the manual deployment piece, at least for pre-prod. We may still want to manually trigger production, at least for a while. As a high level view of the pipeline process, this looks good. I'd like to flesh out some of the specifics.

I am open to considering autodeploy for pre-prod - I'd like to get dev team perspective as they are the main stakeholders. However, autodeploy to PROD is off the table for now - its too risky for an unproven dev team. In fact, I'd like to restrict the PROD deployment to manual and only through a Jenkins release build, thereby making it very intentional. I'd like to flesh out the specifics of the entire release pipeline and get the devs following that process consistently (at least a few release) before we implement autodeploy PROD. Developer buy-in to this standard release pipeline is critical and forms foundation for everything else. 

> Do we have a written PR process? Something that defines how we want them to be structured and submitted in terms of rebasing/not rebasing, etc? For step 2, we can offset a growing storage problem by using something like the free version of Artifactory to store/cache all of the artifacts Jenkins has to retrieve for each build. That'll speed up builds, also.

- PR process is not defined currently. 
- I thought about Artifactory for this exact purpose and release artifact management. If you'd like to investigate more, go ahead and create an issue and link it here.
- For the time being, "fast builds" are a "nice-to-have" but not essential.

> I typically think of a "dev" server as "whatever's most current in the develop branch", which could be in a number of states, but allows us to constantly iterate. That fits with just automatically deploying code as it gets pushed to that branch. That being said, it also makes it much messier to stage code before a production deployment. So we'll either want to more tightly control what gets pushed to dev, or have a staging environment. The former shortens the iteration loop during development, the latter adds cost.
I'd like to see what the devs think. I do lean towards having auto-deploy for dev server and restrict push activity targeting 'develop'. I'd like to see DEVS work on issue branches and submit PR for merging into develop. Again, this depends on developer buy-in.

**Comment by TKsM151** [comment]
>I am open to considering autodeploy for pre-prod - I'd like to get dev team perspective as they are the main stakeholders. However, autodeploy to PROD is off the table for now - its too risky for an unproven dev team. In fact, I'd like to restrict the PROD deployment to manual and only through a Jenkins release build, thereby making it very intentional (see above screencap: "Example - Deploy to PROD server from 'master' Jenkins Release build").

Please keep auto deploy off for now on the prod instance, we do have master as a protected branch requiring approvals for now as a soft protection but having a disabled auto deploy is safer for now. 
From a dev prospective we would keep the master branch as protected and enable auto deploy once the process is tested and development moving more smoothly, its pretty **choppy** here at the beginning trying to get misc shit out the door. We would require maybe 3 approvals or so on the master branch which would then in turn kick off the jenkins auto deploy.

**Comment by DEVxALMIGHTY** [comment]
@TKsM151 100% agreed on no auto deploy in PROD for now.

Also, don't worry. Before I configured Jenkins auto-deploy in **ANY** environment, I'd communicate my intentions to the team and get buy-in. We will work closely together on this to make sure we are not causing issues in the midst of trying to establish a CICD pipeline.

As we discussed, we can work on configuring auto-deploy for the DO box tonight. And that task is what this issue is supposed to represent - nothing else.

**Comment by DEVxALMIGHTY** [comment]
I've configured auto deploy to the DO box tonight.

@TKsM151 Can you make a change on develop branch? This should trigger the Jenkins build, ssh the content to DO box and update the site.

# Result
![image](https://user-images.githubusercontent.com/37675911/37946298-5135ce36-314a-11e8-9e68-2c4529b5d25b.png)

**Comment by DEVxALMIGHTY** [comment]
Alright sftp via SSH now occurs as part of Jenkins build on DEV DO box!

# Current dev pipeline
1. Developer performs Git commit
2. Jenkins autodeploy
3. Developer manually restarts server to to see changes

Next step is to restart server during Jenkins build using
`bin/console server:start 159.65.243.54:8000`
Afterwards, process will be
1. Developer performs Git commit
2. Jenkins autodeploy
3. After Jenkins build - f5 webpage to see your changes in DEV!

**Comment by DEVxALMIGHTY** [comment]
It seems that the Jenkins "Publish Over SSH" plugin will not publish empty directories. This is a problem because successful deployment of app requires certain empty dirs on the server. For example, `/var/www/therealgd/translations/overrides` . 

I'm investigating a solution.

**Comment by DEVxALMIGHTY** [comment]
There is a checkbox option to sftp empty dirs - completely missed it due to staying up past bedtime!

Tried it out and it worked on `/var/www/therealgd/translations/overrides` .

thanks @kudakeru !

**Comment by DEVxALMIGHTY** [comment]
This is starting to overlap with #93 to the point of redundancy - closing.
