### ISSUE TITLE
Replace browser favicon with Piggo

### ISSUE THREAD

**Issue by DEVxALMIGHTY** [TheRealGD/therealgd#58]
Replace browser favicon with Piggo. It's currently a rifle of some sort.

# Example 1
![image](https://user-images.githubusercontent.com/37675911/37922613-a1f1b2b6-30f2-11e8-9165-b699164c3834.png)

# Example 2
![image](https://user-images.githubusercontent.com/37675911/37922807-4138323c-30f3-11e8-8485-35515af69d1e.png)

**Comment by TKsM151** [comment]
Self reminder: og:image needs fix too

**Comment by TKsM151** [comment]
Replaced with piggo, w transparency bg, also fixed og:image and added bunch of ios/android image metas
