### ISSUE TITLE
Navbar hover effect

### ISSUE THREAD

**Issue by DEVxALMIGHTY** [TheRealGD/therealgd#59]
Improve end-user experience by implementing a mouse-hover effect on the site's navbar. When a user hovers over the boundary of a selectable item on the navbar, change color of the item. In the mockups shown below, the user is hovering over "Categories" item in the navbar. 

Also, remove the hover:underline effect - it will be redundant after this feature is implemented.

This should be implemented for the following navbar items:

1. Gundeals
2. Categories
3. Wiki
4. Login
5. Signup

# Mockup - lighter purple as hover color ?
![image](https://user-images.githubusercontent.com/37675911/37925591-8ebd8564-30fa-11e8-92a1-d7a12fbf0909.png)

# Mockup - gray as hover color ?
![image](https://user-images.githubusercontent.com/37675911/37925643-b1a0fd5e-30fa-11e8-8f2f-ef0fcd48468d.png)

**Comment by DEVxALMIGHTY** [comment]
Added to v3 but this should be trivial to implement in CSS. So it could realistically make v1.

**Comment by psineur** [comment]
ligther purple
