### ISSUE TITLE
Setup DB cluster/replicaset with Backup with Prod/Dev(s) DBs and Tools

### ISSUE THREAD

**Issue by psineur** [TheRealGD/therealgd#6]
IMO can be done like this, would be happy to learn that I'm wrong by someone who takes this task and executes the crap out of it! 🏆 

- [x] Setup single replicaset (or whatever name is for Postgres) with multiple DBs: Dev, Staging, Prod.
- [x] Dev DB needs barely enough protections/permissions so one dev doesn't screw other over.
- [x] Setup backup for whole replicaset
- [ ] Optionally: DevDB for every Dev, distribute through Discord
- [x] Provide scripts or even straight automate copying data from Staging / Prod to DevDBs - so we have more data to test features/development against.

Useful links in case noob has to do this:
 - https://zaiste.net/backup_postgresql_to_amazon_s3/ - I have currently something similar but for RocksDB for my startup. Should be pretty simple to setup.
 - https://s3-backups.readthedocs.io/en/latest/

I haven't really had much experience with PostgreSQL, blame @alexeylang lol (hey look we're messing with Symfony, where's Vanya? =) ).

Would prefer actual DBA work on this. Please assign to yourself if you volunteer.

Complete implementation of this is kinda-blocked by our decision to run on AWS, so stick to standard Unix ways and write-up instructions / installation scripts when possible.
Commiting these to this repo under db/ or whatnot is highly encouraged.

**Comment by psineur** [comment]
https://s3-backups.readthedocs.io/en/latest/

**Comment by psineur** [comment]
This is kinda semi-blocked by us making a choice in our first hosting

**Comment by psineur** [comment]
I haven't really had much experience with PostgreSQL, blame @AlexeyLang lol (hey look we're messing with Symfony, where's Vanya? =) ).

Would prefer actual DBA work on this. Please assign to yourself if you volunteer.

**Comment by psineur** [comment]
Updated, now it's more of an everything DB before MVP task.

**Comment by NathanDeckinga** [comment]
This might need to be assigned to me.  But I think this is a smaller thing than described.  If the DDL is going to be controlled by Symfony (the application), then really all we need to do on a database side is create the DB and set up a couple of users with appropriate permissions.  And if it is AWS, then either vanilla RDS or Aurora RDS (Postgres either way) makes this a matter of a couple of minutes.

**Comment by psineur** [comment]
@NathanDeckinga

How should we store secrets and forward them to APP box(es)?

**Comment by NathanDeckinga** [comment]
I think the only secrets that will be needed are the passwords and we could go with a password vault for that (simplest solution).  I'm not sure how the app will need to store that internally, but we could go with some AWS credential storage, but that ties us closer to AWS than we probably want to be.

**Comment by psineur** [comment]
This is awesome write-up @NathanDeckinga Thank You!
I'll ask in security group about what password vault we want to use for secrets.

**Comment by psineur** [comment]
After looking at vault, SSM and some other stuff - I'm seriously considering simply starting with  AWS instancedata:

```
    #!/bin/bash
    curl -s http://169.254.169.254/latest/user-data > ./.env
    service php7.1-fpm restart #not sure if restart is needed
    nginx -s reload #not sure if reload is needed
```

Pros of SSM or Vault:
 - secrets are encrypted
 - secrets can be rotated and other cool mature-prod stuff can be done with it
Cons:
 - someone with access to token and www-box still will be able to retrieve the secret
 - we don't have that many secrets / config strings really - using a service is kinda an overkill at this point

**Comment by psineur** [comment]
OK, I have RDS on my AWS account working with @nautbot 's devbox through VPC peer connection.

**Comment by psineur** [comment]
A Record set propageted to my ISP, post works, lives in new RDS:

https://gundeals.io/f/toxic_masculinity/1/this-is-micro-box-that-is-working-against-new-rds-now

**Comment by psineur** [comment]
@NathanDeckinga TKsM and DEVxALMIGHTY have access to this box now, use them if I'm not available.

**Comment by NathanDeckinga** [comment]
@psineur  - Sorry for the delay, I was unreachable the past 2 days.  I'm 100% good with an AWS solution like that.  I've used it before and it works well with minimal setup and maintenance.  My one caveat is that the goal was to not use AWS specific stuff, and that's AWS specific.  It's also not a decision that I felt okay to make without application development support.

**Comment by psineur** [comment]
Updated #54 , checked 
 - [ ] Provide scripts or even straight automate copying data from Staging / Prod to DevDBs - so we have more data to test features/development against.

Task is kill
