### ISSUE TITLE
Alternate (simpler) site favicon

### ISSUE THREAD

**Issue by DEVxALMIGHTY** [TheRealGD/therealgd#83]
The site favicon has a bit too much going on and its hard to tell exactly what it is due to it small size. Piggo is cool but a more clean & simple favicon is in order. Below are a few mockups.

The one furthest right is closest to our current branding. I'm not sure what the font is currently in 'GUNDEALS' site header? @nautbot @psineur 

This task might be within Semper's ability ? 

We, of course, will need a vector.

---

![image](https://user-images.githubusercontent.com/37675911/37973947-4c389ab0-31a1-11e8-8315-da21fbfe7d34.png)

**Comment by psineur** [comment]
Last one is the best.
Lets try it with Antique Olive font

**Comment by DEVxALMIGHTY** [comment]
Agreed last is best

Semper is learning in & outs of illustrator & will start work on this soon.

**Comment by TKsM151** [comment]
I will get the Vector project from the creator of Piggo so that Semper can check it out as well. so I added myself to this issue as well.

**Comment by TKsM151** [comment]
Generated new SVG with "GD" make new issue if needed for new design
